kabam_msgs/Waypoint waypoint_info #ID can be blank if creating new waypoint
bool delete_waypoint
---
uint8 RESULT_WAYPOINT_CREATED=0
uint8 RESULT_MAP_NOT_FOUND=1
uint8 RESULT_WAYPOINT_NAME_ALREADY_EXISTS_IN_SAME_MAP=2
uint8 RESULT_WAYPOINT_UPDATED=3
uint8 RESULT_WAYPOINT_NOT_FOUND=4
uint8 RESULT_WAYPOINT_DELETED=5
uint8 RESULT_UNDEFINED_FAILURE=6
uint8 result
kabam_msgs/Waypoint waypoint_response #return with ID in creating waypoint

