kabam_msgs/waypoint waypoint_info #ID can be blank if creating new waypoint
bool delete
---
uint8 RESULT_WAYPOINT_CREATED=0
uint8 RESULT_WAYPOINT_NAME_ALREADY_EXISTS_IN_SAME_MAP=1
uint8 RESULT_WAYPOINT_UPDATED=2
uint8 RESULT_WAYPOINT_NOT_FOUND=3
uint8 RESULT_WAYPOINT_DELETED=4
uint8 RESULT_UNDEFINED_FAILURE=5
uint8 result
kabam_msgs/waypoint waypoint_response #return with ID in creating waypoint

